#!/usr/bin/env node
var fs = require('fs');
var assert = require('assert');

var input = fs.readFileSync('./input.feature').toString();
var expectedOutput = fs.readFileSync('./output.feature').toString();
var expandDefinitions = require('../');
var output = expandDefinitions(input);
assert.equal(output, expectedOutput, 'Output and expected output do not match.');

console.log('Test succeeded!');
