#!/usr/bin/env node
var fs = require('fs');

var input = fs.readFileSync('./input.feature').toString();
var expectedOutput = fs.readFileSync('./output.feature').toString();
var expandDefinitions = require('../');
var output = expandDefinitions(input);

if (output === expectedOutput) {
    return console.log('Test succeeded!');
} else {
    var errorMsg = 'Output and expected output do not match.';
    console.log('Tests failed: ' + errorMsg);
    console.log('--- OUTPUT ---');
    console.log(output);
    console.log('--- EXPECTED ---');
    console.log(expectedOutput);
    throw new Error(errorMsg);
}
