#!/usr/bin/env node
var fs = require('fs');
var assert = require('assert');

var input = fs.readFileSync('./input.feature').toString();
var expectedOutput = fs.readFileSync('./output.feature').toString();
var pullDefinitions = require('../').pullDefinitions;
var insertDefinitions = require('../').insertDefinitions;
var between = pullDefinitions(input);
var output = insertDefinitions(between);
assert.equal(output, expectedOutput, 'Output and expected output do not match.');

console.log('Test succeeded!');
